# vim: ft=yaml
---
driver:
  name: vagrant
  customize: 
    memory: 1024

provisioner:
  name: salt_solo
  formula: blackfire-formula
  state_top:
    base:
      "*":
        - blackfire-formula

platforms:
  - name: bento/debian-8.2

suites:
  - name: default

  - name: custom
    provisioner:
      pillars-from-files:
        blackfire-formula.sls: pillar-custom.sls
      pillars:
        top.sls:
          base:
            "*":
              - blackfire-formula

